'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { verifyMfaChallenge } from '../../actions';
import { toast } from 'sonner';
import { verifyMfaSchema } from '@/lib/validations/auth';
import { PinInput } from '@/components/forms/pin-input';
import { TurnstileWidget } from '@/components/forms/turnstile-widget';
import { AuthLayout } from '@/components/layout/auth-layout';

type VerifyMfaValues = z.infer<typeof verifyMfaSchema>;
const FONT_STACK = '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';

export default function TwoFactorChallengePage() {
  const [loading, setLoading] = useState(false);
  const [turnstileToken, setTurnstileToken] = useState<string | null>(null);
  const [turnstileExpired, setTurnstileExpired] = useState(false);

  const { handleSubmit, setValue, watch, formState: { errors } } = useForm<VerifyMfaValues>({
    resolver: zodResolver(verifyMfaSchema),
    mode: 'all',
  });

  const tokenValue = watch('token');

  const onSubmit = async (data: VerifyMfaValues) => {
    if (turnstileExpired) {
      toast.error('Security check has expired. Please verify again.');
      return;
    }
    setLoading(true);
    const formData = new FormData();
    formData.append('token', data.token);
    if (turnstileToken) {
      formData.append('turnstileToken', turnstileToken);
    }
    
    const res = await verifyMfaChallenge(formData);
    
    if (res?.error) {
      toast.error(res.error);
      setLoading(false);
    }
  };
  
  return (
    <AuthLayout>
      <div className="auth-fade-in" style={{ width: '100%', float: 'left' }}>
        <div className="auth-stagger-1">
          <h3 style={{ fontSize: '28px', fontWeight: 500, color: 'hsl(var(--foreground))', marginBottom: '8px', lineHeight: '33.6px', fontFamily: FONT_STACK }}>
            Two-factor authentication
          </h3>
          <p style={{ fontSize: '13px', color: 'hsl(var(--muted-foreground))', marginBottom: '16px', lineHeight: '19.5px', fontFamily: FONT_STACK }}>
            Enter the 6-digit security code generated by your authenticator app.
          </p>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} style={{ width: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <div className="auth-stagger-2" style={{ padding: '16px 0 8px 0' }}>
            <PinInput 
              value={tokenValue || ''}
              onChange={(val) => setValue('token', val, { shouldValidate: true })}
            />
          </div>
          {errors.token && <p style={{ fontSize: '11px', color: 'hsl(var(--destructive))', marginTop: '4px', fontFamily: FONT_STACK }}>{errors.token.message}</p>}

          {/* Cloudflare Turnstile — Bot Protection */}
          <div className="auth-stagger-3" style={{ width: '100%', marginTop: '8px' }}>
            <TurnstileWidget
              variant="inline"
              onVerify={(token) => {
                setTurnstileToken(token);
                setTurnstileExpired(false);
              }}
              onError={() => {
                setTurnstileToken(null);
                toast.error('Security check failed. Please refresh and try again.');
              }}
              onExpire={() => {
                setTurnstileToken(null);
                setTurnstileExpired(true);
              }}
            />
            {turnstileExpired && (
              <p style={{ fontSize: '11px', color: 'hsl(var(--destructive))', marginTop: '4px', textAlign: 'center', fontFamily: FONT_STACK }}>
                Security check expired. Please re-verify.
              </p>
            )}
          </div>

          <div className="login-con auth-stagger-4" style={{ width: '100%', marginTop: '10px' }}>
            <button
              type="submit"
              disabled={loading || (tokenValue?.length !== 6)}
              className="btn btn-primary btn-main auth-btn-primary"
              style={{
                width: '100%',
                height: '33px',
                padding: '6px 28px',
                fontSize: '13px',
                lineHeight: '19.5px',
                backgroundColor: '#29A4FF',
                color: '#ffffff',
                fontWeight: 700,
                borderRadius: '6px',
                border: '0',
                cursor: loading || (tokenValue?.length !== 6) ? 'not-allowed' : 'pointer',
                textAlign: 'center',
                boxSizing: 'border-box',
                fontFamily: FONT_STACK,
                opacity: loading || (tokenValue?.length !== 6) ? 0.7 : 1,
              }}
            >
              {loading ? 'Verifying code...' : 'Verify code'}
            </button>
          </div>

          <div className="text-center auth-stagger-5" style={{ marginTop: '16px', display: 'flex', justifyContent: 'center', gap: '6px', alignItems: 'center' }}>
            <Link
              href="/login"
              style={{ color: '#29A4FF', fontSize: '12px', textDecoration: 'none', fontWeight: 600, fontFamily: FONT_STACK, transition: 'opacity 0.2s' }}
              className="hover:opacity-80"
            >
              Back to sign in
            </Link>
          </div>
        </form>
      </div>
    </AuthLayout>
  );
}
