export const typography = {
  display: {
    fontFamily: "var(--font-sans)",
    fontSize: "4.5rem",
    fontWeight: "700",
    lineHeight: "1.1",
    letterSpacing: "-0.02em",
  },
  h1: {
    fontFamily: "var(--font-sans)",
    fontSize: "3rem",
    fontWeight: "700",
    lineHeight: "1.1",
    letterSpacing: "-0.02em",
  },
  h2: {
    fontFamily: "var(--font-sans)",
    fontSize: "2.25rem",
    fontWeight: "600",
    lineHeight: "1.2",
    letterSpacing: "-0.01em",
  },
  h3: {
    fontFamily: "var(--font-sans)",
    fontSize: "1.875rem",
    fontWeight: "600",
    lineHeight: "1.2",
    letterSpacing: "-0.01em",
  },
  h4: {
    fontFamily: "var(--font-sans)",
    fontSize: "1.5rem",
    fontWeight: "600",
    lineHeight: "1.3",
    letterSpacing: "-0.01em",
  },
  h5: {
    fontFamily: "var(--font-sans)",
    fontSize: "1.25rem",
    fontWeight: "600",
    lineHeight: "1.4",
    letterSpacing: "normal",
  },
  bodyLg: {
    fontFamily: "var(--font-sans)",
    fontSize: "1.125rem",
    fontWeight: "400",
    lineHeight: "1.7",
    letterSpacing: "normal",
  },
  body: {
    fontFamily: "var(--font-sans)",
    fontSize: "1rem",
    fontWeight: "400",
    lineHeight: "1.5",
    letterSpacing: "normal",
  },
  bodySm: {
    fontFamily: "var(--font-sans)",
    fontSize: "0.875rem",
    fontWeight: "400",
    lineHeight: "1.4",
    letterSpacing: "normal",
  },
  caption: {
    fontFamily: "var(--font-sans)",
    fontSize: "0.75rem",
    fontWeight: "400",
    lineHeight: "1.3",
    letterSpacing: "normal",
  },
  label: {
    fontFamily: "var(--font-sans)",
    fontSize: "0.875rem",
    fontWeight: "500",
    lineHeight: "1",
    letterSpacing: "normal",
  },
  overline: {
    fontFamily: "var(--font-sans)",
    fontSize: "0.75rem",
    fontWeight: "600",
    lineHeight: "1.2",
    letterSpacing: "0.05em",
  },
  code: {
    fontFamily: "var(--font-mono)",
    fontSize: "0.875rem",
    fontWeight: "400",
    lineHeight: "1.4",
    letterSpacing: "normal",
  },
};
